<template>
  <section class="mx-auto max-w-6xl space-y-6">
    <header class="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p class="text-sm font-semibold uppercase tracking-[0.16em] text-[var(--accent-hover)]">Portfolio content</p><h1 class="mt-2 text-3xl font-bold text-pretty">Education</h1><p class="mt-2 text-sm text-[var(--foreground-secondary)]">Keep academic history current and choose what appears publicly.</p></div><NuxtLink to="/admin/education/new" class="inline-flex min-h-11 items-center justify-center rounded-md bg-[var(--accent-primary)] px-4 text-sm font-semibold text-white hover:bg-[var(--accent-hover)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--border-focus)]">Add education</NuxtLink></header>
    <div v-if="successMessage" class="rounded-md border border-emerald-700/30 bg-emerald-50 px-4 py-3 text-sm text-emerald-900" role="status" aria-live="polite">{{ successMessage }}</div><div v-if="actionError" class="rounded-md border border-red-700/30 bg-red-50 px-4 py-3 text-sm text-red-900" role="alert">{{ actionError }}</div>
    <div v-if="pending" class="space-y-3" aria-busy="true" aria-label="Loading education"><div v-for="n in 3" :key="n" class="h-24 animate-pulse rounded-lg bg-[var(--background-muted)]" /></div>
    <div v-else-if="loadError" class="rounded-lg border border-red-700/30 bg-[var(--background-card)] p-6" role="alert"><h2 class="font-semibold">Education could not be loaded</h2><button type="button" class="mt-4 min-h-11 rounded-md border border-[var(--border-subtle)] px-4 text-sm font-semibold focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--border-focus)]" @click="retry">Try again</button></div>
    <div v-else-if="!items.length" class="rounded-lg border border-dashed border-[var(--border-subtle)] bg-[var(--background-card)] p-10 text-center"><h2 class="font-semibold">No education entries yet</h2><p class="mt-2 text-sm text-[var(--foreground-secondary)]">Add a school or program to complete the portfolio.</p><NuxtLink to="/admin/education/new" class="mt-5 inline-flex min-h-11 items-center rounded-md border border-[var(--accent-primary)] px-4 text-sm font-semibold text-[var(--accent-hover)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--border-focus)]">Add an entry</NuxtLink></div>
    <div v-else class="grid gap-3"> <article v-for="item in items" :key="item.id" class="rounded-lg border border-[var(--border-subtle)] bg-[var(--background-card)] p-4 shadow-[var(--shadow-sm)] sm:p-5"><div class="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div class="min-w-0"><div class="flex flex-wrap items-center gap-2"><h2 class="break-words text-lg font-semibold">{{ item.institution }}</h2><span class="rounded-full px-2.5 py-1 text-xs font-semibold" :class="item.is_published ? 'bg-emerald-100 text-emerald-900' : 'bg-[var(--background-muted)] text-[var(--foreground-secondary)]'">{{ item.is_published ? 'Published' : 'Draft' }}</span></div><p class="mt-1 text-sm text-[var(--foreground-secondary)]">{{ item.degree }}</p><p class="mt-2 text-xs text-[var(--foreground-muted)]">{{ formatRange(item) }}</p></div><div class="flex flex-wrap gap-2"><NuxtLink :to="`/admin/education/${item.id}`" class="inline-flex min-h-11 items-center rounded-md border border-[var(--border-subtle)] px-3 text-sm font-semibold hover:border-[var(--accent-primary)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--border-focus)]">Edit</NuxtLink><button type="button" class="inline-flex min-h-11 items-center rounded-md border border-[var(--border-subtle)] px-3 text-sm font-semibold hover:border-[var(--accent-primary)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--border-focus)] disabled:opacity-60" :disabled="busyId === item.id" @click="togglePublished(item)">{{ busyId === item.id ? 'Updating…' : item.is_published ? 'Unpublish' : 'Publish' }}</button><button type="button" class="inline-flex min-h-11 items-center rounded-md border border-red-700/40 px-3 text-sm font-semibold text-red-800 hover:bg-red-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-red-700" @click="openDelete(item)">Delete</button></div></div></article></div>
    <dialog ref="deleteDialog" class="w-[min(100%-2rem,32rem)] rounded-lg border border-[var(--border-subtle)] bg-[var(--background-card)] p-0 shadow-[var(--shadow-lg)] backdrop:bg-[var(--color-obsidian)]/50" aria-labelledby="education-delete-title"><div class="p-6"><h2 id="education-delete-title" class="text-xl font-semibold">Delete education entry?</h2><p class="mt-2 text-sm text-[var(--foreground-secondary)]">“{{ deleteTarget?.institution }}” will be permanently removed.</p><div class="mt-6 flex flex-col-reverse gap-3 sm:flex-row sm:justify-end"><button ref="cancelDeleteButton" type="button" class="min-h-11 rounded-md border border-[var(--border-subtle)] px-4 text-sm font-semibold focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--border-focus)]" @click="closeDelete">Cancel</button><button type="button" class="min-h-11 rounded-md bg-red-800 px-4 text-sm font-semibold text-white focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-red-700 disabled:opacity-60" :disabled="Boolean(deletingId)" @click="confirmDelete">{{ deletingId ? 'Deleting…' : 'Delete entry' }}</button></div></div></dialog>
  </section>
</template>

<script setup lang="ts">
definePageMeta({ layout: 'admin', middleware: ['auth'] })
interface Education { id: string; institution: string; degree: string; start_date: string | null; end_date: string | null; is_expected: boolean; is_published: boolean }
const { data, pending, error: loadError, refresh } = await useFetch<Education[]>('/api/admin/education')
const items = computed(() => data.value ?? [])
const deleteDialog = ref<HTMLDialogElement | null>(null); const cancelDeleteButton = ref<HTMLButtonElement | null>(null); const deleteTarget = ref<Education | null>(null)
const busyId = ref(''); const deletingId = ref(''); const actionError = ref(''); const successMessage = ref('')
const formatDate = (value: string | null) => value ? new Intl.DateTimeFormat('en', { month: 'short', year: 'numeric' }).format(new Date(`${value}T00:00:00`)) : ''
const formatRange = (item: Education) => `${formatDate(item.start_date)} – ${item.end_date ? formatDate(item.end_date) : item.is_expected ? 'Expected' : 'Present'}`
const retry = async () => { actionError.value = ''; await refresh() }
const togglePublished = async (item: Education) => { busyId.value = item.id; actionError.value = ''; try { await $fetch(`/api/admin/education/${item.id}`, { method: 'PUT', body: { is_published: !item.is_published } }); successMessage.value = item.is_published ? 'Education entry unpublished.' : 'Education entry published.'; await refresh() } catch (error) { actionError.value = error instanceof Error ? error.message : 'Unable to update publication status.' } finally { busyId.value = '' } }
const openDelete = (item: Education) => { deleteTarget.value = item; deleteDialog.value?.showModal(); nextTick(() => cancelDeleteButton.value?.focus()) }
const closeDelete = () => { deleteDialog.value?.close(); deleteTarget.value = null }
const confirmDelete = async () => { if (!deleteTarget.value) return; deletingId.value = deleteTarget.value.id; actionError.value = ''; try { await $fetch(`/api/admin/education/${deleteTarget.value.id}`, { method: 'DELETE' }); successMessage.value = 'Education entry deleted.'; closeDelete(); await refresh() } catch (error) { actionError.value = error instanceof Error ? error.message : 'Unable to delete this entry.' } finally { deletingId.value = '' } }
</script>
