<template>
  <section class="mx-auto max-w-6xl space-y-6">
    <header><p class="text-sm font-semibold uppercase tracking-[0.16em] text-[var(--accent-hover)]">Inbox</p><h1 class="mt-2 text-3xl font-bold text-pretty">Contact messages</h1><p class="mt-2 max-w-2xl text-sm text-[var(--foreground-secondary)]">Review messages sent from the public contact form. Message text is displayed as text, never as HTML.</p></header>
    <div v-if="successMessage" class="rounded-md border border-emerald-700/30 bg-emerald-50 px-4 py-3 text-sm text-emerald-900" role="status" aria-live="polite">{{ successMessage }}</div><div v-if="actionError" class="rounded-md border border-red-700/30 bg-red-50 px-4 py-3 text-sm text-red-900" role="alert">{{ actionError }}</div>
    <div v-if="pending" class="space-y-3" aria-busy="true" aria-label="Loading contact messages"><div v-for="n in 3" :key="n" class="h-36 animate-pulse rounded-lg bg-[var(--background-muted)]" /></div><div v-else-if="loadError" class="rounded-lg border border-red-700/30 bg-[var(--background-card)] p-6" role="alert"><h2 class="font-semibold">Messages could not be loaded</h2><p class="mt-1 text-sm text-[var(--foreground-secondary)]">Check your connection, then try again.</p><button type="button" class="mt-4 min-h-11 rounded-md border border-[var(--border-subtle)] px-4 text-sm font-semibold focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--border-focus)]" @click="retry">Try again</button></div><div v-else-if="!messages.length" class="rounded-lg border border-dashed border-[var(--border-subtle)] bg-[var(--background-card)] p-10 text-center"><h2 class="font-semibold">Your inbox is clear</h2><p class="mt-2 text-sm text-[var(--foreground-secondary)]">New contact form submissions will appear here.</p></div><div v-else class="grid gap-4"><article v-for="message in messages" :key="message.id" class="rounded-lg border bg-[var(--background-card)] p-4 shadow-[var(--shadow-sm)] sm:p-5" :class="message.is_read ? 'border-[var(--border-subtle)]' : 'border-[var(--accent-primary)]'"><div class="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div class="min-w-0"><div class="flex flex-wrap items-center gap-2"><h2 class="break-words text-lg font-semibold">{{ message.name }}</h2><span class="rounded-full px-2.5 py-1 text-xs font-semibold" :class="message.is_read ? 'bg-[var(--background-muted)] text-[var(--foreground-secondary)]' : 'bg-[var(--accent-primary)] text-white'">{{ message.is_read ? 'Read' : 'Unread' }}</span></div><a :href="`mailto:${message.email}`" class="mt-1 inline-block break-all text-sm text-[var(--accent-hover)] underline-offset-2 hover:underline focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--border-focus)]">{{ message.email }}</a><p class="mt-2 text-xs text-[var(--foreground-muted)]">{{ formatDate(message.created_at) }}</p></div><button type="button" class="inline-flex min-h-11 shrink-0 items-center justify-center rounded-md border border-[var(--border-subtle)] px-3 text-sm font-semibold hover:border-[var(--accent-primary)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--border-focus)] disabled:opacity-60" :disabled="updatingId === message.id" :aria-busy="updatingId === message.id" @click="toggleRead(message)">{{ updatingId === message.id ? 'Updating…' : message.is_read ? 'Mark unread' : 'Mark read' }}</button></div><p class="mt-5 whitespace-pre-wrap break-words border-t border-[var(--border-subtle)] pt-4 text-sm leading-7 text-[var(--foreground-secondary)]">{{ message.message }}</p></article></div>
  </section>
</template>
<script setup lang="ts">
definePageMeta({ layout: 'admin', middleware: ['auth'] })
interface Message { id: string; name: string; email: string; message: string; created_at: string; is_read: boolean }
const { data, pending, error: loadError, refresh } = await useFetch<Message[]>('/api/admin/contact-messages'); const messages = computed(() => data.value ?? []); const updatingId = ref(''); const actionError = ref(''); const successMessage = ref('')
const formatDate = (value: string) => new Intl.DateTimeFormat('en', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)); const retry = async () => { actionError.value = ''; await refresh() }
const toggleRead = async (message: Message) => { updatingId.value = message.id; actionError.value = ''; try { await $fetch(`/api/admin/contact-messages/${message.id}`, { method: 'PUT', body: { is_read: !message.is_read } }); successMessage.value = message.is_read ? 'Message marked unread.' : 'Message marked read.'; await refresh() } catch (error) { actionError.value = error instanceof Error ? error.message : 'Unable to update this message.' } finally { updatingId.value = '' } }
</script>
